language: node_js
cache: npm
node_js:
  - "14"
script:
  - npm run build
  - npm run test
  - sonar-scanner
addons:
  sonarcloud:
    organization: exportarts
    token:
      secure: "BXVVo8grrfQaGaVPjYQGu5CuBLO3Ke5UbyFHjusmGNsavCiJqYA+GMJm/86oQUhOvwCeExdIfRpL3039mMKbgLakkzkreXyBvnsV4T/XnED5fGz8RgP2tpXmZsJRdxeEh8jRbetaIuCQWg2kyOifhZKwobBzNErM++HHGX2M0NE78uznAvJwUVPTez1d6o6xUnfpL0eJ0emQpmAE5ZQ6a8bNUng6uWiaodk3ZuFXPBtsgbm8lyxPulF2KSCq77GpV0iPHRO2Bdfki6ouEF+srkWsN5GL5qF0OL8uPcSH6ZaFsd87Me5I3IyiFxIlqjs7WFOyuIyzPb+30GGAkW48LEejLA8IDr9ezLSkIXLV2wufMdrntxzJtmgF+bECURMxWTcoS706M7WgzB5ugJ2sI77Z9DB92oHngDiE+wJFDH/GSivQr/h9rJRQSdu5nHRHJpqBsz344gG+AdemljKwEI1zGrrPBwgDoiVWUpaO3SVUHnRHezLEH7cLgEK942DmQ2YijK6iVVoAhUo1YT7XA0IB5Gytw2OaQuXHTPBPnJCfiVE2k02KwbnbqjtM4AO/BX39v32+MFWUx9uqWoq9d4TfGmKk5+ZLPbjUxivXrvlERnF6ejyhXHDlj4o/84KMk/T9iSFkSDp5OVvybYcSuvuDZXRcUgoU4MjrggAVXl8="
